version: "3.6"

services:

  remote-provisioner:
    build: ./build/terraform
    image: local-hashicorp/terraform:latest
    container_name: remote-provisioner
    environment:
      PROJECT_ROOT: ${PROJECT_ROOT:-/tmp/project-root}
      TERRAFORM_DIR: ${TERRAFORM_DIR:-terraform}
      TERRAFORM_OPTIONS: ${TERRAFORM_OPTIONS:-}
    volumes:
      - ../:${PROJECT_ROOT:-/tmp/project-root}
      - ${HOME}/.aws:/home/terraform/.aws:ro
    entrypoint: ${PROJECT_ROOT:-/tmp/project-root}/entrypoint.sh
