version: "3.6"

services:

  remote-provisioner:
    build: ./build/terraform
    image: local-hashicorp/terraform:0.12.5
    container_name: remote-provisioner
    environment:
      PROJECT_ROOT: ${PROJECT_ROOT:-/tmp/project-root}
      TERRAFORM_DIR: ${TERRAFORM_DIR:-terraform}
      TERRAFORM_OPTIONS: ${TERRAFORM_OPTIONS:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ../:${PROJECT_ROOT:-/tmp/project-root}
      - ${HOME}/.aws:/home/terraform/.aws:ro
    entrypoint: ${PROJECT_ROOT:-/tmp/project-root}/entrypoint.sh
